
CREATE TABLE T_Person
(FName
VARCHAR(20),FAge
INT,FRemark
VARCHAR(20),PRIMARY KEY (FName));CREATE TABLE T_Debt (FNumber VARCHAR(20),FAmount DECIMAL(10,2) NOT
NULL,
FPerson VARCHAR(20),PRIMARY KEY (FNumber),
FOREIGN KEY (FPerson) REFERENCES T_Person(FName)) ;
